### ISSUE TITLE
I was not able to use the sample after downloading it

### ISSUE THREAD

**Issue by LMClaboratory** [anaestheticsapp/bluetooth#1]
Since it is very interesting work, I have downloaded the files, uncompressed them, and tried to start the index.html file in the src2 folder. Unfortunately, a black page opened without graphics or other objects.

May someone help me in using the code?

**Comment by anaestheticsapp** [comment]
You will need a web server to open the index file.

You can just go to the link in the demo instead to try out the app.

What pulse oximeter do you have?

**Comment by goperderian** [comment]
Awesome Demo! I love this demo. Can you add rollup.config.js?

**Comment by anaestheticsapp** [comment]
Yep will do at some point tomorrow

**Comment by anaestheticsapp** [comment]
Added the rollup config

**Comment by goperderian** [comment]
@anaestheticsapp do you have experience in connecting with iHealth Pulse Oximeter?
https://ihealthlabs.com/products/ihealth-air-pulse-oximeter

**Comment by anaestheticsapp** [comment]
Sadly not but they should all be very similar

**Comment by goperderian** [comment]
Yeah, the device has these services: 
00001800-0000-1000-8000-00805f9b34fb, 
00001801-0000-1000-8000-00805f9b34fb, 
0000180a-0000-1000-8000-00805f9b34fb, 
636f6d2e-6a69-7561-6e2e-504f56313100
-------------------------------------------

636f6d2e-6a69-7561-6e2e-504f56313100
This service has the notify property. 

```
service 636f6d2e-6a69-7561-6e2e-504f56313100
{uuid: '7274782e', description: 'BTLE-Value-here'}
```

But couldn't read the SpO2 and HR.

Do you have any idea? 

Thank you
